### ISSUE TITLE
Make compatible with Nexus 5 and similar devices

### ISSUE THREAD

**Issue by gentlecat** [jdamcd/musicbrainz-android#75]

**Comment by enpatrik** [comment]
Hi, any updates on a possible new release? I wanted to try out the app on my Nexus5 but ran into this issue when trying to install it.

**Comment by Jimmyson** [comment]
I have this running on my Nexus 5 and has not been an issue. Had previously used the base Google OS image and currently using a Lineage OS image.

There are no issues to report, and so far cannot remember if the Play Store prevented me from installing this app.
